[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "5PhUntsPKb3696HVDJgDBj4EHj1TLP2oFxSZ8oP7vx8f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/someguy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
