[package]
name = "program_client"
version = "0.1.0"
edition = "2018"
[dependencies.trident-client]
version = "0.6.0"

[dependencies.hello_world]
path = "../programs/hello_world"
features = ["no-entrypoint"]
